//! Missing definitions from `#include <WinPerf.h>` to augment `windows::Win32::System::Performance` module.
#![allow(bad_style, unused)]

use windows::Win32::System::Performance::*;

pub const PERF_COUNTER_COUNTER: u32 = PERF_SIZE_DWORD | PERF_TYPE_COUNTER | PERF_COUNTER_RATE
    | PERF_TIMER_TICK | PERF_DELTA_COUNTER | PERF_DISPLAY_PER_SEC;
pub const PERF_COUNTER_TIMER: u32 = PERF_SIZE_LARGE | PERF_TYPE_COUNTER | PERF_COUNTER_RATE
    | PERF_TIMER_TICK | PERF_DELTA_COUNTER | PERF_DISPLAY_PERCENT;
pub const PERF_COUNTER_QUEUELEN_TYPE: u32 = PERF_SIZE_DWORD | PERF_TYPE_COUNTER
    | PERF_COUNTER_QUEUELEN | PERF_TIMER_TICK | PERF_DELTA_COUNTER | PERF_DISPLAY_NO_SUFFIX;
pub const PERF_COUNTER_LARGE_QUEUELEN_TYPE: u32 = PERF_SIZE_LARGE | PERF_TYPE_COUNTER
    | PERF_COUNTER_QUEUELEN | PERF_TIMER_TICK | PERF_DELTA_COUNTER | PERF_DISPLAY_NO_SUFFIX;
pub const PERF_COUNTER_100NS_QUEUELEN_TYPE: u32 = PERF_SIZE_LARGE | PERF_TYPE_COUNTER
    | PERF_COUNTER_QUEUELEN | PERF_TIMER_100NS | PERF_DELTA_COUNTER | PERF_DISPLAY_NO_SUFFIX;
pub const PERF_COUNTER_OBJ_TIME_QUEUELEN_TYPE: u32 = PERF_SIZE_LARGE | PERF_TYPE_COUNTER
    | PERF_COUNTER_QUEUELEN | PERF_OBJECT_TIMER | PERF_DELTA_COUNTER | PERF_DISPLAY_NO_SUFFIX;
pub const PERF_COUNTER_BULK_COUNT: u32 = PERF_SIZE_LARGE | PERF_TYPE_COUNTER | PERF_COUNTER_RATE
    | PERF_TIMER_TICK | PERF_DELTA_COUNTER | PERF_DISPLAY_PER_SEC;
pub const PERF_COUNTER_TEXT: u32 = PERF_SIZE_VARIABLE_LEN | PERF_TYPE_TEXT | PERF_TEXT_UNICODE
    | PERF_DISPLAY_NO_SUFFIX;
pub const PERF_COUNTER_RAWCOUNT: u32 = PERF_SIZE_DWORD | PERF_TYPE_NUMBER | PERF_NUMBER_DECIMAL
    | PERF_DISPLAY_NO_SUFFIX;
pub const PERF_COUNTER_LARGE_RAWCOUNT: u32 = PERF_SIZE_LARGE | PERF_TYPE_NUMBER
    | PERF_NUMBER_DECIMAL | PERF_DISPLAY_NO_SUFFIX;
pub const PERF_COUNTER_RAWCOUNT_HEX: u32 = PERF_SIZE_DWORD | PERF_TYPE_NUMBER | PERF_NUMBER_HEX
    | PERF_DISPLAY_NO_SUFFIX;
pub const PERF_COUNTER_LARGE_RAWCOUNT_HEX: u32 = PERF_SIZE_LARGE | PERF_TYPE_NUMBER
    | PERF_NUMBER_HEX | PERF_DISPLAY_NO_SUFFIX;
pub const PERF_SAMPLE_FRACTION: u32 = PERF_SIZE_DWORD | PERF_TYPE_COUNTER
    | PERF_COUNTER_FRACTION | PERF_DELTA_COUNTER | PERF_DELTA_BASE | PERF_DISPLAY_PERCENT;
pub const PERF_SAMPLE_COUNTER: u32 = PERF_SIZE_DWORD | PERF_TYPE_COUNTER | PERF_COUNTER_RATE
    | PERF_TIMER_TICK | PERF_DELTA_COUNTER | PERF_DISPLAY_NO_SUFFIX;
pub const PERF_COUNTER_NODATA: u32 = PERF_SIZE_ZERO | PERF_DISPLAY_NOSHOW;
pub const PERF_COUNTER_TIMER_INV: u32 = PERF_SIZE_LARGE | PERF_TYPE_COUNTER | PERF_COUNTER_RATE
    | PERF_TIMER_TICK | PERF_DELTA_COUNTER | PERF_INVERSE_COUNTER | PERF_DISPLAY_PERCENT;
pub const PERF_SAMPLE_BASE: u32 = PERF_SIZE_DWORD | PERF_TYPE_COUNTER | PERF_COUNTER_BASE
    | PERF_DISPLAY_NOSHOW | 0x00000001;
pub const PERF_AVERAGE_TIMER: u32 = PERF_SIZE_DWORD | PERF_TYPE_COUNTER | PERF_COUNTER_FRACTION
    | PERF_DISPLAY_SECONDS;
pub const PERF_AVERAGE_BASE: u32 = PERF_SIZE_DWORD | PERF_TYPE_COUNTER | PERF_COUNTER_BASE
    | PERF_DISPLAY_NOSHOW | 0x00000002;
pub const PERF_AVERAGE_BULK: u32 = PERF_SIZE_LARGE | PERF_TYPE_COUNTER | PERF_COUNTER_FRACTION
    | PERF_DISPLAY_NOSHOW;
pub const PERF_OBJ_TIME_TIMER: u32 = PERF_SIZE_LARGE | PERF_TYPE_COUNTER | PERF_COUNTER_RATE
    | PERF_OBJECT_TIMER | PERF_DELTA_COUNTER | PERF_DISPLAY_PERCENT;
pub const PERF_100NSEC_TIMER: u32 = PERF_SIZE_LARGE | PERF_TYPE_COUNTER | PERF_COUNTER_RATE
    | PERF_TIMER_100NS | PERF_DELTA_COUNTER | PERF_DISPLAY_PERCENT;
pub const PERF_100NSEC_TIMER_INV: u32 = PERF_SIZE_LARGE | PERF_TYPE_COUNTER | PERF_COUNTER_RATE
    | PERF_TIMER_100NS | PERF_DELTA_COUNTER | PERF_INVERSE_COUNTER | PERF_DISPLAY_PERCENT;
pub const PERF_COUNTER_MULTI_TIMER: u32 = PERF_SIZE_LARGE | PERF_TYPE_COUNTER
    | PERF_COUNTER_RATE | PERF_DELTA_COUNTER | PERF_TIMER_TICK | PERF_MULTI_COUNTER
    | PERF_DISPLAY_PERCENT;
pub const PERF_COUNTER_MULTI_TIMER_INV: u32 = PERF_SIZE_LARGE | PERF_TYPE_COUNTER
    | PERF_COUNTER_RATE | PERF_DELTA_COUNTER | PERF_MULTI_COUNTER | PERF_TIMER_TICK
    | PERF_INVERSE_COUNTER | PERF_DISPLAY_PERCENT;
pub const PERF_COUNTER_MULTI_BASE: u32 = PERF_SIZE_LARGE | PERF_TYPE_COUNTER | PERF_COUNTER_BASE
    | PERF_MULTI_COUNTER | PERF_DISPLAY_NOSHOW;
pub const PERF_100NSEC_MULTI_TIMER: u32 = PERF_SIZE_LARGE | PERF_TYPE_COUNTER
    | PERF_DELTA_COUNTER | PERF_COUNTER_RATE | PERF_TIMER_100NS | PERF_MULTI_COUNTER
    | PERF_DISPLAY_PERCENT;
pub const PERF_100NSEC_MULTI_TIMER_INV: u32 = PERF_SIZE_LARGE | PERF_TYPE_COUNTER
    | PERF_DELTA_COUNTER | PERF_COUNTER_RATE | PERF_TIMER_100NS | PERF_MULTI_COUNTER
    | PERF_INVERSE_COUNTER | PERF_DISPLAY_PERCENT;
pub const PERF_RAW_FRACTION: u32 = PERF_SIZE_DWORD | PERF_TYPE_COUNTER | PERF_COUNTER_FRACTION
    | PERF_DISPLAY_PERCENT;
pub const PERF_LARGE_RAW_FRACTION: u32 = PERF_SIZE_LARGE | PERF_TYPE_COUNTER
    | PERF_COUNTER_FRACTION | PERF_DISPLAY_PERCENT;
pub const PERF_RAW_BASE: u32 = PERF_SIZE_DWORD | PERF_TYPE_COUNTER | PERF_COUNTER_BASE
    | PERF_DISPLAY_NOSHOW | 0x00000003;
pub const PERF_LARGE_RAW_BASE: u32 = PERF_SIZE_LARGE | PERF_TYPE_COUNTER | PERF_COUNTER_BASE
    | PERF_DISPLAY_NOSHOW;
pub const PERF_ELAPSED_TIME: u32 = PERF_SIZE_LARGE | PERF_TYPE_COUNTER | PERF_COUNTER_ELAPSED
    | PERF_OBJECT_TIMER | PERF_DISPLAY_SECONDS;
pub const PERF_COUNTER_DELTA: u32 = PERF_SIZE_DWORD | PERF_TYPE_COUNTER | PERF_COUNTER_VALUE
    | PERF_DELTA_COUNTER | PERF_DISPLAY_NO_SUFFIX;
pub const PERF_COUNTER_LARGE_DELTA: u32 = PERF_SIZE_LARGE | PERF_TYPE_COUNTER
    | PERF_COUNTER_VALUE | PERF_DELTA_COUNTER | PERF_DISPLAY_NO_SUFFIX;
pub const PERF_PRECISION_SYSTEM_TIMER: u32 = PERF_SIZE_LARGE | PERF_TYPE_COUNTER
    | PERF_COUNTER_PRECISION | PERF_TIMER_TICK | PERF_DELTA_COUNTER | PERF_DISPLAY_PERCENT;
pub const PERF_PRECISION_100NS_TIMER: u32 = PERF_SIZE_LARGE | PERF_TYPE_COUNTER
    | PERF_COUNTER_PRECISION | PERF_TIMER_100NS | PERF_DELTA_COUNTER | PERF_DISPLAY_PERCENT;
pub const PERF_PRECISION_OBJECT_TIMER: u32 = PERF_SIZE_LARGE | PERF_TYPE_COUNTER
    | PERF_COUNTER_PRECISION | PERF_OBJECT_TIMER | PERF_DELTA_COUNTER | PERF_DISPLAY_PERCENT;
pub const PERF_PRECISION_TIMESTAMP: u32 = PERF_LARGE_RAW_BASE;
