//! Bindings to the `#include <WinPerf.h>`
#![allow(bad_style, overflowing_literals, unused_macros)]

use winapi::shared::minwindef::*;
use winapi::shared::ntdef::*;
use winapi::um::minwinbase::SYSTEMTIME;

pub const PERF_DATA_VERSION: DWORD = 1;
pub const PERF_DATA_REVISION: DWORD = 1;
STRUCT!{struct PERF_DATA_BLOCK {
    Signature: [WCHAR; 4],
    LittleEndian: DWORD,
    Version: DWORD,
    Revision: DWORD,
    TotalByteLength: DWORD,
    HeaderLength: DWORD,
    NumObjectTypes: DWORD,
    DefaultObject: LONG,
    SystemTime: SYSTEMTIME,
    PerfTime: LARGE_INTEGER,
    PerfFreq: LARGE_INTEGER,
    PerfTime100nSec: LARGE_INTEGER,
    SystemNameLength: DWORD,
    SystemNameOffset: DWORD,
}}
pub type PPERF_DATA_BLOCK = *mut PERF_DATA_BLOCK;
#[cfg(target_arch = "x86_64")]
STRUCT!{struct PERF_OBJECT_TYPE {
    TotalByteLength: DWORD,
    DefinitionLength: DWORD,
    HeaderLength: DWORD,
    ObjectNameTitleIndex: DWORD,
    ObjectNameTitle: DWORD,
    ObjectHelpTitleIndex: DWORD,
    ObjectHelpTitle: DWORD,
    DetailLevel: DWORD,
    NumCounters: DWORD,
    DefaultCounter: LONG,
    NumInstances: LONG,
    CodePage: DWORD,
    PerfTime: LARGE_INTEGER,
    PerfFreq: LARGE_INTEGER,
}}
#[cfg(target_arch = "x86")]
STRUCT!{struct PERF_OBJECT_TYPE {
    TotalByteLength: DWORD,
    DefinitionLength: DWORD,
    HeaderLength: DWORD,
    ObjectNameTitleIndex: DWORD,
    ObjectNameTitle: LPWSTR,
    ObjectHelpTitleIndex: DWORD,
    ObjectHelpTitle: LPWSTR,
    DetailLevel: DWORD,
    NumCounters: DWORD,
    DefaultCounter: LONG,
    NumInstances: LONG,
    CodePage: DWORD,
    PerfTime: LARGE_INTEGER,
    PerfFreq: LARGE_INTEGER,
}}
pub type PPERF_OBJECT_TYPE = *mut PERF_OBJECT_TYPE;
pub const PERF_NO_INSTANCES: LONG = -1;
pub const PERF_SIZE_DWORD: DWORD = 0x00000000;
pub const PERF_SIZE_LARGE: DWORD = 0x00000100;
pub const PERF_SIZE_ZERO: DWORD = 0x00000200;
pub const PERF_SIZE_VARIABLE_LEN: DWORD = 0x00000300;
pub const PERF_TYPE_NUMBER: DWORD = 0x00000000;
pub const PERF_TYPE_COUNTER: DWORD = 0x00000400;
pub const PERF_TYPE_TEXT: DWORD = 0x00000800;
pub const PERF_TYPE_ZERO: DWORD = 0x00000C00;
pub const PERF_NUMBER_HEX: DWORD = 0x00000000;
pub const PERF_NUMBER_DECIMAL: DWORD = 0x00010000;
pub const PERF_NUMBER_DEC_1000: DWORD = 0x00020000;
pub const PERF_COUNTER_VALUE: DWORD = 0x00000000;
pub const PERF_COUNTER_RATE: DWORD = 0x00010000;
pub const PERF_COUNTER_FRACTION: DWORD = 0x00020000;
pub const PERF_COUNTER_BASE: DWORD = 0x00030000;
pub const PERF_COUNTER_ELAPSED: DWORD = 0x00040000;
pub const PERF_COUNTER_QUEUELEN: DWORD = 0x00050000;
pub const PERF_COUNTER_HISTOGRAM: DWORD = 0x00060000;
pub const PERF_COUNTER_PRECISION: DWORD = 0x00070000;
pub const PERF_TEXT_UNICODE: DWORD = 0x00000000;
pub const PERF_TEXT_ASCII: DWORD = 0x00010000;
pub const PERF_TIMER_TICK: DWORD = 0x00000000;
pub const PERF_TIMER_100NS: DWORD = 0x00100000;
pub const PERF_OBJECT_TIMER: DWORD = 0x00200000;
pub const PERF_DELTA_COUNTER: DWORD = 0x00400000;
pub const PERF_DELTA_BASE: DWORD = 0x00800000;
pub const PERF_INVERSE_COUNTER: DWORD = 0x01000000;
pub const PERF_MULTI_COUNTER: DWORD = 0x02000000;
pub const PERF_DISPLAY_NO_SUFFIX: DWORD = 0x00000000;
pub const PERF_DISPLAY_PER_SEC: DWORD = 0x10000000;
pub const PERF_DISPLAY_PERCENT: DWORD = 0x20000000;
pub const PERF_DISPLAY_SECONDS: DWORD = 0x30000000;
pub const PERF_DISPLAY_NOSHOW: DWORD = 0x40000000;
pub const PERF_COUNTER_COUNTER: DWORD = PERF_SIZE_DWORD | PERF_TYPE_COUNTER | PERF_COUNTER_RATE
    | PERF_TIMER_TICK | PERF_DELTA_COUNTER | PERF_DISPLAY_PER_SEC;
pub const PERF_COUNTER_TIMER: DWORD = PERF_SIZE_LARGE | PERF_TYPE_COUNTER | PERF_COUNTER_RATE
    | PERF_TIMER_TICK | PERF_DELTA_COUNTER | PERF_DISPLAY_PERCENT;
pub const PERF_COUNTER_QUEUELEN_TYPE: DWORD = PERF_SIZE_DWORD | PERF_TYPE_COUNTER
    | PERF_COUNTER_QUEUELEN | PERF_TIMER_TICK | PERF_DELTA_COUNTER | PERF_DISPLAY_NO_SUFFIX;
pub const PERF_COUNTER_LARGE_QUEUELEN_TYPE: DWORD = PERF_SIZE_LARGE | PERF_TYPE_COUNTER
    | PERF_COUNTER_QUEUELEN | PERF_TIMER_TICK | PERF_DELTA_COUNTER | PERF_DISPLAY_NO_SUFFIX;
pub const PERF_COUNTER_100NS_QUEUELEN_TYPE: DWORD = PERF_SIZE_LARGE | PERF_TYPE_COUNTER
    | PERF_COUNTER_QUEUELEN | PERF_TIMER_100NS | PERF_DELTA_COUNTER | PERF_DISPLAY_NO_SUFFIX;
pub const PERF_COUNTER_OBJ_TIME_QUEUELEN_TYPE: DWORD = PERF_SIZE_LARGE | PERF_TYPE_COUNTER
    | PERF_COUNTER_QUEUELEN | PERF_OBJECT_TIMER | PERF_DELTA_COUNTER | PERF_DISPLAY_NO_SUFFIX;
pub const PERF_COUNTER_BULK_COUNT: DWORD = PERF_SIZE_LARGE | PERF_TYPE_COUNTER | PERF_COUNTER_RATE
    | PERF_TIMER_TICK | PERF_DELTA_COUNTER | PERF_DISPLAY_PER_SEC;
pub const PERF_COUNTER_TEXT: DWORD = PERF_SIZE_VARIABLE_LEN | PERF_TYPE_TEXT | PERF_TEXT_UNICODE
    | PERF_DISPLAY_NO_SUFFIX;
pub const PERF_COUNTER_RAWCOUNT: DWORD = PERF_SIZE_DWORD | PERF_TYPE_NUMBER | PERF_NUMBER_DECIMAL
    | PERF_DISPLAY_NO_SUFFIX;
pub const PERF_COUNTER_LARGE_RAWCOUNT: DWORD = PERF_SIZE_LARGE | PERF_TYPE_NUMBER
    | PERF_NUMBER_DECIMAL | PERF_DISPLAY_NO_SUFFIX;
pub const PERF_COUNTER_RAWCOUNT_HEX: DWORD = PERF_SIZE_DWORD | PERF_TYPE_NUMBER | PERF_NUMBER_HEX
    | PERF_DISPLAY_NO_SUFFIX;
pub const PERF_COUNTER_LARGE_RAWCOUNT_HEX: DWORD = PERF_SIZE_LARGE | PERF_TYPE_NUMBER
    | PERF_NUMBER_HEX | PERF_DISPLAY_NO_SUFFIX;
pub const PERF_SAMPLE_FRACTION: DWORD = PERF_SIZE_DWORD | PERF_TYPE_COUNTER
    | PERF_COUNTER_FRACTION | PERF_DELTA_COUNTER | PERF_DELTA_BASE | PERF_DISPLAY_PERCENT;
pub const PERF_SAMPLE_COUNTER: DWORD = PERF_SIZE_DWORD | PERF_TYPE_COUNTER | PERF_COUNTER_RATE
    | PERF_TIMER_TICK | PERF_DELTA_COUNTER | PERF_DISPLAY_NO_SUFFIX;
pub const PERF_COUNTER_NODATA: DWORD = PERF_SIZE_ZERO | PERF_DISPLAY_NOSHOW;
pub const PERF_COUNTER_TIMER_INV: DWORD = PERF_SIZE_LARGE | PERF_TYPE_COUNTER | PERF_COUNTER_RATE
    | PERF_TIMER_TICK | PERF_DELTA_COUNTER | PERF_INVERSE_COUNTER | PERF_DISPLAY_PERCENT;
pub const PERF_SAMPLE_BASE: DWORD = PERF_SIZE_DWORD | PERF_TYPE_COUNTER | PERF_COUNTER_BASE
    | PERF_DISPLAY_NOSHOW | 0x00000001;
pub const PERF_AVERAGE_TIMER: DWORD = PERF_SIZE_DWORD | PERF_TYPE_COUNTER | PERF_COUNTER_FRACTION
    | PERF_DISPLAY_SECONDS;
pub const PERF_AVERAGE_BASE: DWORD = PERF_SIZE_DWORD | PERF_TYPE_COUNTER | PERF_COUNTER_BASE
    | PERF_DISPLAY_NOSHOW | 0x00000002;
pub const PERF_AVERAGE_BULK: DWORD = PERF_SIZE_LARGE | PERF_TYPE_COUNTER | PERF_COUNTER_FRACTION
    | PERF_DISPLAY_NOSHOW;
pub const PERF_OBJ_TIME_TIMER: DWORD = PERF_SIZE_LARGE | PERF_TYPE_COUNTER | PERF_COUNTER_RATE
    | PERF_OBJECT_TIMER | PERF_DELTA_COUNTER | PERF_DISPLAY_PERCENT;
pub const PERF_100NSEC_TIMER: DWORD = PERF_SIZE_LARGE | PERF_TYPE_COUNTER | PERF_COUNTER_RATE
    | PERF_TIMER_100NS | PERF_DELTA_COUNTER | PERF_DISPLAY_PERCENT;
pub const PERF_100NSEC_TIMER_INV: DWORD = PERF_SIZE_LARGE | PERF_TYPE_COUNTER | PERF_COUNTER_RATE
    | PERF_TIMER_100NS | PERF_DELTA_COUNTER | PERF_INVERSE_COUNTER | PERF_DISPLAY_PERCENT;
pub const PERF_COUNTER_MULTI_TIMER: DWORD = PERF_SIZE_LARGE | PERF_TYPE_COUNTER
    | PERF_COUNTER_RATE | PERF_DELTA_COUNTER | PERF_TIMER_TICK | PERF_MULTI_COUNTER
    | PERF_DISPLAY_PERCENT;
pub const PERF_COUNTER_MULTI_TIMER_INV: DWORD = PERF_SIZE_LARGE | PERF_TYPE_COUNTER
    | PERF_COUNTER_RATE | PERF_DELTA_COUNTER | PERF_MULTI_COUNTER | PERF_TIMER_TICK
    | PERF_INVERSE_COUNTER | PERF_DISPLAY_PERCENT;
pub const PERF_COUNTER_MULTI_BASE: DWORD = PERF_SIZE_LARGE | PERF_TYPE_COUNTER | PERF_COUNTER_BASE
    | PERF_MULTI_COUNTER | PERF_DISPLAY_NOSHOW;
pub const PERF_100NSEC_MULTI_TIMER: DWORD = PERF_SIZE_LARGE | PERF_TYPE_COUNTER
    | PERF_DELTA_COUNTER | PERF_COUNTER_RATE | PERF_TIMER_100NS | PERF_MULTI_COUNTER
    | PERF_DISPLAY_PERCENT;
pub const PERF_100NSEC_MULTI_TIMER_INV: DWORD = PERF_SIZE_LARGE | PERF_TYPE_COUNTER
    | PERF_DELTA_COUNTER | PERF_COUNTER_RATE | PERF_TIMER_100NS | PERF_MULTI_COUNTER
    | PERF_INVERSE_COUNTER | PERF_DISPLAY_PERCENT;
pub const PERF_RAW_FRACTION: DWORD = PERF_SIZE_DWORD | PERF_TYPE_COUNTER | PERF_COUNTER_FRACTION
    | PERF_DISPLAY_PERCENT;
pub const PERF_LARGE_RAW_FRACTION: DWORD = PERF_SIZE_LARGE | PERF_TYPE_COUNTER
    | PERF_COUNTER_FRACTION | PERF_DISPLAY_PERCENT;
pub const PERF_RAW_BASE: DWORD = PERF_SIZE_DWORD | PERF_TYPE_COUNTER | PERF_COUNTER_BASE
    | PERF_DISPLAY_NOSHOW | 0x00000003;
pub const PERF_LARGE_RAW_BASE: DWORD = PERF_SIZE_LARGE | PERF_TYPE_COUNTER | PERF_COUNTER_BASE
    | PERF_DISPLAY_NOSHOW;
pub const PERF_ELAPSED_TIME: DWORD = PERF_SIZE_LARGE | PERF_TYPE_COUNTER | PERF_COUNTER_ELAPSED
    | PERF_OBJECT_TIMER | PERF_DISPLAY_SECONDS;
pub const PERF_COUNTER_HISTOGRAM_TYPE: DWORD = 0x80000000;
pub const PERF_COUNTER_DELTA: DWORD = PERF_SIZE_DWORD | PERF_TYPE_COUNTER | PERF_COUNTER_VALUE
    | PERF_DELTA_COUNTER | PERF_DISPLAY_NO_SUFFIX;
pub const PERF_COUNTER_LARGE_DELTA: DWORD = PERF_SIZE_LARGE | PERF_TYPE_COUNTER
    | PERF_COUNTER_VALUE | PERF_DELTA_COUNTER | PERF_DISPLAY_NO_SUFFIX;
pub const PERF_PRECISION_SYSTEM_TIMER: DWORD = PERF_SIZE_LARGE | PERF_TYPE_COUNTER
    | PERF_COUNTER_PRECISION | PERF_TIMER_TICK | PERF_DELTA_COUNTER | PERF_DISPLAY_PERCENT;
pub const PERF_PRECISION_100NS_TIMER: DWORD = PERF_SIZE_LARGE | PERF_TYPE_COUNTER
    | PERF_COUNTER_PRECISION | PERF_TIMER_100NS | PERF_DELTA_COUNTER | PERF_DISPLAY_PERCENT;
pub const PERF_PRECISION_OBJECT_TIMER: DWORD = PERF_SIZE_LARGE | PERF_TYPE_COUNTER
    | PERF_COUNTER_PRECISION | PERF_OBJECT_TIMER | PERF_DELTA_COUNTER | PERF_DISPLAY_PERCENT;
pub const PERF_PRECISION_TIMESTAMP: DWORD = PERF_LARGE_RAW_BASE;
pub const PERF_DETAIL_NOVICE: DWORD = 100;
pub const PERF_DETAIL_ADVANCED: DWORD = 200;
pub const PERF_DETAIL_EXPERT: DWORD = 300;
pub const PERF_DETAIL_WIZARD: DWORD = 400;
#[cfg(target_arch = "x86_64")]
STRUCT!{struct PERF_COUNTER_DEFINITION {
    ByteLength: DWORD,
    CounterNameTitleIndex: DWORD,
    CounterNameTitle: DWORD,
    CounterHelpTitleIndex: DWORD,
    CounterHelpTitle: DWORD,
    DefaultScale: LONG,
    DetailLevel: DWORD,
    CounterType: DWORD,
    CounterSize: DWORD,
    CounterOffset: DWORD,
}}
#[cfg(target_arch = "x86")]
STRUCT!{struct PERF_COUNTER_DEFINITION {
    ByteLength: DWORD,
    CounterNameTitleIndex: DWORD,
    CounterNameTitle: LPWSTR,
    CounterHelpTitleIndex: DWORD,
    CounterHelpTitle: LPWSTR,
    DefaultScale: LONG,
    DetailLevel: DWORD,
    CounterType: DWORD,
    CounterSize: DWORD,
    CounterOffset: DWORD,
}}
pub type PPERF_COUNTER_DEFINITION = *mut PERF_COUNTER_DEFINITION;
pub const PERF_NO_UNIQUE_ID: LONG = -1;
STRUCT!{struct PERF_INSTANCE_DEFINITION {
    ByteLength: DWORD,
    ParentObjectTitleIndex: DWORD,
    ParentObjectInstance: DWORD,
    UniqueID: LONG,
    NameOffset: DWORD,
    NameLength: DWORD,
}}
pub type PPERF_INSTANCE_DEFINITION = *mut PERF_INSTANCE_DEFINITION;
STRUCT!{struct PERF_COUNTER_BLOCK {
    ByteLength: DWORD,
}}
pub type PPERF_COUNTER_BLOCK = *mut PERF_COUNTER_BLOCK;
pub const PERF_QUERY_OBJECTS: LONG = 0x80000000;
pub const PERF_QUERY_GLOBAL: LONG = 0x80000001;
pub const PERF_QUERY_COSTLY: LONG = 0x80000002;
// TODO: use private FN!{} macro
pub type PM_OPEN_PROC = unsafe extern "system" fn(
    pContext: LPWSTR
) -> DWORD;
pub type PM_COLLECT_PROC = unsafe extern "system" fn(
    lpValueName: LPWSTR,
    lppData: *mut LPVOID,
    lpcbTotalBytes: LPDWORD,
    lpNumObjectTypes: LPDWORD,
) -> DWORD;
pub type PM_CLOSE_PROC = unsafe extern "system" fn() -> DWORD;
pub type PM_QUERY_PROC = unsafe extern "system" fn(LPDWORD, *mut LPVOID, LPDWORD, LPDWORD) -> DWORD;
// TODO: conditional define on MAX_PERF_OBJECTS_IN_QUERY_FUNCTION
