[package]
name = "rtsm-proto"
version = "0.1.0"
authors = ["ivan tkachenko <ratijas@users.noreply.github.com>"]
edition = "2024"

[lib]
name = "rtsm_proto"

[dependencies]
morse-stream = { path = "../morse-stream" }
